BASE = "https://dantri.com.vn/rss"

FEEDS = {
    "trang-chu":          f"{BASE}/home.rss",
    "su-kien":            f"{BASE}/su-kien.rss",
    "thoi-su":            f"{BASE}/thoi-su.rss",
    "the-gioi":           f"{BASE}/the-gioi.rss",
    "gia-vang":           f"{BASE}/gia-vang.rss",
    "doi-song":           f"{BASE}/doi-song.rss",
    "the-thao":           f"{BASE}/the-thao.rss",
    "lao-dong-viec-lam":  f"{BASE}/lao-dong-viec-lam.rss",
    "giao-duc":           f"{BASE}/giao-duc.rss",
    "tam-long-nhan-ai":   f"{BASE}/tam-long-nhan-ai.rss",
    "kinh-doanh":         f"{BASE}/kinh-doanh.rss",
    "bat-dong-san":       f"{BASE}/bat-dong-san.rss",
    "giai-tri":           f"{BASE}/giai-tri.rss",
    "du-lich":            f"{BASE}/du-lich.rss",
    "phap-luat":          f"{BASE}/phap-luat.rss",
    "suc-khoe":           f"{BASE}/suc-khoe.rss",
    "cong-nghe":          f"{BASE}/cong-nghe.rss",
    "o-to-xe-may":        f"{BASE}/o-to-xe-may.rss",
    "tinh-yeu-gioi-tinh": f"{BASE}/tinh-yeu-gioi-tinh.rss",
    "khoa-hoc":           f"{BASE}/khoa-hoc.rss",
    "noi-vu":             f"{BASE}/noi-vu.rss",
    "ban-doc":            f"{BASE}/ban-doc.rss",
    "tam-diem":           f"{BASE}/tam-diem.rss",
    "dmagazine":          f"{BASE}/dmagazine.rss",
    "infographic":        f"{BASE}/infographic.rss",
    "photo-news":         f"{BASE}/photo-news.rss",
    "dnews":              f"{BASE}/dnews.rss",
    "toa-dam-truc-tuyen": f"{BASE}/toa-dam-truc-tuyen.rss",
    "xo-so":              f"{BASE}/xo-so.rss",
    "interactive":        f"{BASE}/interactive.rss",
    "tet":                f"{BASE}/tet.rss",
    "photo-story":        f"{BASE}/photo-story.rss",
    "d-buzz":             f"{BASE}/d-buzz.rss",
    "thoi-tiet":          f"{BASE}/thoi-tiet.rss",
    "dt360":              f"{BASE}/dt360.rss",
}
